/*
-----------------------------------------------------------------------------
Filename:    cadogAnimationControl.h
-----------------------------------------------------------------------------


This source file is generated by the
   ___                   _              __    __ _                  _
  /___\__ _ _ __ ___    /_\  _ __  _ __/ / /\ \ (_)______ _ _ __ __| |
 //  // _` | '__/ _ \  //_\\| '_ \| '_ \ \/  \/ / |_  / _` | '__/ _` |
/ \_// (_| | | |  __/ /  _  \ |_) | |_) \  /\  /| |/ / (_| | | | (_| |
\___/ \__, |_|  \___| \_/ \_/ .__/| .__/ \/  \/ |_/___\__,_|_|  \__,_|
      |___/                 |_|   |_|
	  Ogre 1.7.x Application Wizard for Code::Blocks (May 2010)
	  http://code.google.com/p/ogreappwizards/
-----------------------------------------------------------------------------
*/

#ifndef __CADOGANIMATIONCONTROL_H_XXX
#define __CADOGANIMATIONCONTROL_H_XXX

#include "cadogApplication.h"
#include "cadog.h"

struct AnimationControl{


    virtual void init(Ogre::Entity* ent, Ogre::SceneNode* node,const char* state);
    virtual ~AnimationControl(void);

    virtual void move(Ogre::Vector3 mDestination);
    void acelerate();
    void reduce();
    virtual void showMove(const Ogre::FrameEvent &evt,bool& movComp,const char* ws, const char* is1, const char* is2);
    virtual void showMoveSin(const Ogre::FrameEvent &evt,bool& movComp,const char* ws, const char* is1, const char* is2);
    virtual void setSpeed(Ogre::Real speed);


    Ogre::Real mDistance;                  // The distance the object has left to travel
    Ogre::Vector3 mDirection;              // The direction the object is moving
    Ogre::Vector3 mDestination;            // The destination the object is moving towards

    Ogre::AnimationState *mAnimationState; // The current animation state of the object

    Ogre::Entity *mEntity;                 // The Entity we are animating
    Ogre::SceneNode *mNode;                // The SceneNode that the Entity is attached to

    Ogre::Real accRate;//Velocidade de corrida
    Ogre::Real mWalkSpeed;                 // The speed at which the object is moving
    Ogre::Real mWaitTime;                   //Tempo de espera entre um movimento e outro

    Ogre::Real hmax; //controla altura do movimento
    Ogre::Real frequence;//frenquencia de ocilacao
    Ogre::Real ho; //Altura inicial
    Ogre::Real tAcc;//Tempo acumulado

};

#endif

