/*
-----------------------------------------------------------------------------
Filename:    cadogMainMenu.cpp
-----------------------------------------------------------------------------


This source file is generated by the
   ___                   _              __    __ _                  _
  /___\__ _ _ __ ___    /_\  _ __  _ __/ / /\ \ (_)______ _ _ __ __| |
 //  // _` | '__/ _ \  //_\\| '_ \| '_ \ \/  \/ / |_  / _` | '__/ _` |
/ \_// (_| | | |  __/ /  _  \ |_) | |_) \  /\  /| |/ / (_| | | | (_| |
\___/ \__, |_|  \___| \_/ \_/ .__/| .__/ \/  \/ |_/___\__,_|_|  \__,_|
      |___/                 |_|   |_|
	  Ogre 1.7.x Application Wizard for Code::Blocks (May 2010)
	  http://code.google.com/p/ogreappwizards/
-----------------------------------------------------------------------------
*/

#include "cadogMainMenu.h"


cadogMainMenu::cadogMainMenu(OgreBites::SdkTrayManager* mTM)
{
    mTrayManager=mTM;
    newGameButton=mTrayManager->createButton(OgreBites::TL_CENTER, "NewGame", "New Game");
    newGameButton->show();
}

cadogMainMenu::~cadogMainMenu()
{

}

void cadogMainMenu::hide()
{
    newGameButton->hide();
    mTrayManager->hideCursor();
    mTrayManager->removeWidgetFromTray("NewGame");
}

void cadogMainMenu::show()
{
    mTrayManager->showCursor();
    mTrayManager->moveWidgetToTray("NewGame", OgreBites::TL_CENTER);
    newGameButton->show();
    mTrayManager->showAll();
}


